title: Hello word
description: 'I BIENVENU GBETI .I am here to say hello to elders '
template:
  repo: hello-word-template
  name: hello-word
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
